Test = Class.new(ActiveRecord::Base)
Question = Class.new(ActiveRecord::Base)
Option = Class.new(ActiveRecord::Base)
Lesson = Class.new(ActiveRecord::Base)

# Test A
test_a = Test.create(letter: "A", description: "Introducción a Haskell", completed: false, cant_questions: 5, acerted_answers: 0)

lesson_a1 = Lesson.create(number: 1, title: "Introducción a Haskell", description: "En esta lección, aprenderás sobre Haskell, un lenguaje de programación funcional puro. Haskell se basa en la evaluación lazy, lo que significa que los cálculos se posponen hasta que los resultados sean necesarios. Además, Haskell se destaca por su expresividad y concisión en el código. Conocerás los fundamentos de Haskell, su sintaxis y cómo se utiliza para resolver problemas de programación.", test_letter: "A", completed: false)
lesson_a2 = Lesson.create(number: 2, title: "Tipos de datos en Haskell", description: "Los tipos de datos son una parte fundamental en Haskell. Aprenderás sobre los tipos básicos, como enteros, caracteres y booleanos. Además, explorarás los tipos algebraicos, que permiten crear estructuras de datos más complejas. Verás cómo definir tus propios tipos de datos personalizados en Haskell y cómo utilizarlos en tus programas.", test_letter: "A", completed: false)
lesson_a3 = Lesson.create(number: 3, title: "Funciones en Haskell", description: "Las funciones son la piedra angular de la programación en Haskell. Aprenderás cómo definir funciones en Haskell, utilizando patrones de coincidencia y guardias para manejar diferentes casos. También explorarás las funciones de orden superior, que permiten pasar funciones como argumentos o devolver funciones como resultados. Descubrirás cómo aprovechar la composición de funciones y cómo implementar recursión en Haskell.", test_letter: "A", completed: false)
lesson_a4 = Lesson.create(number: 4, title: "Listas en Haskell", description: "Las listas son una estructura de datos esencial en Haskell. Aprenderás cómo trabajar con listas, incluyendo su creación, manipulación y acceso a elementos. Explorarás las funciones de orden superior, como map, filter y foldr, que te ayudarán a transformar y procesar listas de manera eficiente. También verás cómo implementar recursión sobre listas para realizar operaciones más complejas.", test_letter: "A", completed: false)
lesson_a5 = Lesson.create(number: 5, title: "Recursión en Haskell", description: "La recursión es una técnica poderosa en Haskell. Aprenderás cómo utilizar la recursión para resolver problemas de manera elegante y eficiente. Explorarás ejemplos prácticos, como el cálculo de factoriales y la búsqueda en árboles binarios, utilizando funciones recursivas. También descubrirás cómo optimizar funciones recursivas utilizando la recursión de cola.", test_letter: "A", completed: false)

question_a1 = Question.create(number: 1, description: "¿Qué es Haskell?", well_answered: false, test_letter: "A")
question_a2 = Question.create(number: 2, description: "¿Cuál de estos no es un tipo de dato en Haskell?", well_answered: false, test_letter: "A")
question_a3 = Question.create(number: 3, description: "¿Cómo se define una función en Haskell?", well_answered: false, test_letter: "A")
question_a4 = Question.create(number: 4, description: "¿Cómo se crea una lista en Haskell?", well_answered: false, test_letter: "A")
question_a5 = Question.create(number: 5, description: "¿Qué es la recursión en Haskell?", well_answered: false, test_letter: "A")

Option.create(number: 1, description: "Un lenguaje de programación funcional", question_number: 1, correct: true)
Option.create(number: 2, description: "Un lenguaje de programación imperativo", question_number: 1, correct: false)
Option.create(number: 3, description: "Un lenguaje de programación orientado a objetos", question_number: 1, correct: false)
Option.create(number: 4, description: "Un tipo de dato en Haskell", question_number: 2, correct: false)
Option.create(number: 5, description: "Bool", question_number: 2, correct: false)
Option.create(number: 6, description: "Arraylist", question_number: 2, correct: true)
Option.create(number: 7, description: "Usando la palabra clave 'function'", question_number: 3, correct: false)
Option.create(number: 8, description: "Usando el operador '=>'", question_number: 3, correct: false)
Option.create(number: 9, description: "Usando el símbolo '->'", question_number: 3, correct: true)
Option.create(number: 10, description: "Mediante un bucle", question_number: 4, correct: false)
Option.create(number: 11, description: "Usando la palabra clave 'list'", question_number: 4, correct: false)
Option.create(number: 12, description: "Mediante la notación de corchetes", question_number: 4, correct: true)
Option.create(number: 13, description: "Un bucle que se llama a sí mismo", question_number: 5, correct: false)
Option.create(number: 14, description: "Una función que se llama a sí misma", question_number: 5, correct: true)
Option.create(number: 15, description: "Un tipo de dato en Haskell", question_number: 5, correct: false)

# Test B
test_b = Test.create(letter: "B", description: "Conceptos básicos de Haskell", completed: false, cant_questions: 5, acerted_answers: 0)

lesson_b1 = Lesson.create(number: 6, title: "Conceptos básicos de Haskell", description: "En esta lección, repasaremos los conceptos fundamentales de Haskell. Aprenderás sobre su historia y características principales, como la programación funcional y la evaluación lazy. También exploraremos la tipificación estática y fuerte de Haskell, así como su sistema de módulos y funciones puras. Al final de esta lección, comprenderás los conceptos básicos que fundamentan el lenguaje Haskell.", test_letter: "B", completed: false)
lesson_b2 = Lesson.create(number: 7, title: "Estructuras de control en Haskell", description: "Aprenderás cómo utilizar las estructuras de control en Haskell. Descubrirás cómo realizar estructuras condicionales utilizando la expresión if-then-else, así como cómo utilizar estructuras de repetición, como el bucle for y el bucle while. Exploraremos ejemplos prácticos y veremos cómo aprovechar las estructuras de control para controlar el flujo de ejecución en tus programas Haskell.", test_letter: "B", completed: false)
lesson_b3 = Lesson.create(number: 8, title: "Módulos en Haskell", description: "Esta lección se centra en el uso de módulos en Haskell. Aprenderás qué son los módulos y cómo puedes utilizarlos para organizar y reutilizar tu código. Exploraremos cómo importar módulos, cómo definir tus propios módulos y cómo utilizar la declaración de exportación para controlar qué funciones y tipos son visibles fuera del módulo. También discutiremos las mejores prácticas en el uso de módulos en Haskell.", test_letter: "B", completed: false)
lesson_b4 = Lesson.create(number: 9, title: "Manipulación de cadenas en Haskell", description: "Aprenderás cómo manipular cadenas de texto en Haskell. Exploraremos las funciones y operadores disponibles para trabajar con cadenas, incluyendo la concatenación, la búsqueda y la manipulación de caracteres individuales. Descubrirás cómo utilizar las funciones proporcionadas por el módulo Data.Text para realizar operaciones eficientes con cadenas en Haskell. También veremos ejemplos prácticos de manipulación de cadenas en Haskell.", test_letter: "B", completed: false)
lesson_b5 = Lesson.create(number: 10, title: "Programación funcional avanzada en Haskell", description: "En esta lección, exploraremos conceptos avanzados de programación funcional en Haskell. Aprenderás sobre la currificación, que es la transformación de una función de múltiples argumentos en una secuencia de funciones que toman un solo argumento. También descubrirás la aplicación de funciones parciales y las funciones de orden superior, que te permiten crear funciones más flexibles y reutilizables. Al final de esta lección, estarás familiarizado con técnicas avanzadas de programación funcional en Haskell.", test_letter: "B", completed: false)

question_b1 = Question.create(number: 6, description: "¿Cuál es el principal objetivo de Haskell?", well_answered: false, test_letter: "B")
question_b2 = Question.create(number: 7, description: "¿Cómo se realiza una estructura condicional en Haskell?", well_answered: false, test_letter: "B")
question_b3 = Question.create(number: 8, description: "¿Qué son los módulos en Haskell?", well_answered: false, test_letter: "B")
question_b4 = Question.create(number: 9, description: "¿Cómo se concatenan cadenas de texto en Haskell?", well_answered: false, test_letter: "B")
question_b5 = Question.create(number: 10, description: "¿Cuál es el concepto de currificación en Haskell?", well_answered: false, test_letter: "B")

Option.create(number: 16, description: "Permitir la programación funcional", question_number: 6, correct: true)
Option.create(number: 17, description: "Permitir la programación orientada a objetos", question_number: 6, correct: false)
Option.create(number: 18, description: "Permitir la programación imperativa", question_number: 6, correct: false)
Option.create(number: 19, description: "Mediante la estructura if-else", question_number: 7, correct: true)
Option.create(number: 20, description: "Usando la palabra clave 'switch'", question_number: 7, correct: false)
Option.create(number: 21, description: "Usando la estructura for", question_number: 7, correct: false)
Option.create(number: 22, description: "Son bloques de código reutilizables", question_number: 8, correct: true)
Option.create(number: 23, description: "Son operadores matemáticos", question_number: 8, correct: false)
Option.create(number: 24, description: "Son estructuras de datos en Haskell", question_number: 8, correct: false)
Option.create(number: 25, description: "Usando el operador '+'", question_number: 9, correct: false)
Option.create(number: 26, description: "Usando la función 'concat'", question_number: 9, correct: false)
Option.create(number: 27, description: "Usando el operador '++'", question_number: 9, correct: true)
Option.create(number: 28, description: "La aplicación de funciones parciales", question_number: 10, correct: false)
Option.create(number: 29, description: "La aplicación de funciones de orden superior", question_number: 10, correct: false)
Option.create(number: 30, description: "La transformación de funciones de varios argumentos en una secuencia de funciones que toman un solo argumento", question_number: 10, correct: true)

# Test C
test_c = Test.create(letter: "C", description: "Programación funcional en Haskell", completed: false, cant_questions: 5, acerted_answers: 0)

lesson_c1 = Lesson.create(number: 11, title: "Programación funcional en Haskell", description: "En esta lección, exploraremos los conceptos clave de la programación funcional en Haskell. Aprenderás que la programación funcional es un paradigma de programación basado en funciones, donde las funciones son tratadas como ciudadanos de primera clase. Descubrirás cómo Haskell implementa la programación funcional y cómo aprovechar sus características principales, como la inmutabilidad, la evaluación perezosa y las funciones puras. Al final de esta lección, comprenderás los fundamentos de la programación funcional en Haskell.", test_letter: "C", completed: false)
lesson_c2 = Lesson.create(number: 12, title: "Recursión en Haskell", description: "Aprenderás cómo utilizar la recursión para resolver problemas en Haskell. La recursión es un concepto central en Haskell y te permite definir funciones que se llaman a sí mismas para abordar problemas de forma iterativa. Exploraremos ejemplos prácticos de recursión, como la implementación de funciones para calcular factoriales y sumas de números. También discutiremos técnicas para escribir funciones recursivas eficientes y evitar bucles infinitos.", test_letter: "C", completed: false)
lesson_c3 = Lesson.create(number: 13, title: "Composición de funciones en Haskell", description: "Esta lección se enfoca en la composición de funciones en Haskell. Aprenderás qué es la composición de funciones y cómo puedes combinar dos o más funciones para obtener una nueva función. Descubrirás cómo utilizar el operador de composición (.) en Haskell y cómo aplicar la composición de funciones para crear programas más concisos y expresivos. También veremos ejemplos prácticos de la composición de funciones en Haskell.", test_letter: "C", completed: false)
lesson_c4 = Lesson.create(number: 14, title: "Manejo de listas en Haskell", description: "Aprenderás a trabajar con listas y funciones de orden superior en Haskell. Las listas son una estructura de datos fundamental en Haskell y te permiten almacenar y manipular colecciones de elementos. Exploraremos funciones de orden superior, como map, filter y reduce, que te permiten realizar operaciones comunes en listas de manera concisa y elegante. También veremos cómo utilizar patrones de comprensión de listas para generar y transformar listas en Haskell.", test_letter: "C", completed: false)
lesson_c5 = Lesson.create(number: 15, title: "Programación monádica en Haskell", description: "En esta lección, exploraremos el concepto de programación monádica y su uso en Haskell. Las mónadas son una abstracción poderosa que te permite encapsular efectos secundarios en un contexto controlado. Aprenderás qué es una mónada y cómo utilizar las mónadas proporcionadas por Haskell, como Maybe, Either y IO, para trabajar con efectos secundarios de manera segura y modular. Al final de esta lección, comprenderás los fundamentos de la programación monádica y su aplicación en Haskell.", test_letter: "C", completed: false)

question_c1 = Question.create(number: 11, description: "¿Qué es la programación funcional?", well_answered: false, test_letter: "C")
question_c2 = Question.create(number: 12, description: "¿Cuál es el concepto central de la recursión en Haskell?", well_answered: false, test_letter: "C")
question_c3 = Question.create(number: 13, description: "¿Qué es la composición de funciones en Haskell?", well_answered: false, test_letter: "C")
question_c4 = Question.create(number: 14, description: "¿Cómo se realiza el filtrado de una lista en Haskell?", well_answered: false, test_letter: "C")
question_c5 = Question.create(number: 15, description: "¿Qué es una mónada en Haskell?", well_answered: false, test_letter: "C")

Option.create(number: 31, description: "Un paradigma de programación basado en funciones", question_number: 11, correct: true)
Option.create(number: 32, description: "Un paradigma de programación basado en objetos", question_number: 11, correct: false)
Option.create(number: 33, description: "Un paradigma de programación basado en eventos", question_number: 11, correct: false)
Option.create(number: 34, description: "La repetición de un bloque de código", question_number: 12, correct: true)
Option.create(number: 35, description: "La división de un problema en subproblemas más pequeños", question_number: 12, correct: false)
Option.create(number: 36, description: "La agrupación de elementos similares en una lista", question_number: 12, correct: false)
Option.create(number: 37, description: "La combinación de dos o más funciones para obtener una nueva función", question_number: 13, correct: true)
Option.create(number: 38, description: "La separación de una función en varias funciones más pequeñas", question_number: 13, correct: false)
Option.create(number: 39, description: "La aplicación de funciones a una lista", question_number: 13, correct: false)
Option.create(number: 40, description: "Usando la función 'filter'", question_number: 14, correct: true)
Option.create(number: 41, description: "Usando la función 'map'", question_number: 14, correct: false)
Option.create(number: 42, description: "Usando la función 'reduce'", question_number: 14, correct: false)
Option.create(number: 43, description: "Un tipo de dato en Haskell", question_number: 15, correct: true)
Option.create(number: 44, description: "Una función pura en Haskell", question_number: 15, correct: false)
Option.create(number: 45, description: "Un operador lógico en Haskell", question_number: 15, correct: false)

# Test D
test_d = Test.create(letter: "D", description: "Programación intermedia en Haskell", completed: false, cant_questions: 5, acerted_answers: 0)

lesson_d1 = Lesson.create(number: 16, title: "Manejo de excepciones en Haskell", description: "Aprenderás a manejar excepciones en Haskell. Descubrirás cómo utilizar bloques try-catch para capturar y manejar excepciones en tu código. Exploraremos las diferentes excepciones predefinidas en Haskell y cómo puedes crear tus propias excepciones personalizadas. También discutiremos las mejores prácticas para el manejo de excepciones y cómo evitar errores comunes al trabajar con excepciones.", test_letter: "D", completed: false)
lesson_d2 = Lesson.create(number: 17, title: "Programación monádica en Haskell", description: "En esta lección, exploraremos la programación monádica en Haskell. Aprenderás que la programación monádica es un enfoque basado en monoides que te permite encapsular efectos secundarios y cálculos en un contexto controlado. Descubrirás qué es una mónada y cómo utilizar las mónadas en Haskell para escribir código modular y seguro. Veremos ejemplos prácticos de programación monádica en Haskell y cómo combinar múltiples mónadas para abordar situaciones complejas.", test_letter: "D", completed: false)
lesson_d3 = Lesson.create(number: 18, title: "Lectura y escritura de archivos en Haskell", description: "Aprenderás cómo leer y escribir archivos en Haskell. Exploraremos las funciones predefinidas de Haskell, como readFile y writeFile, que te permiten interactuar con archivos en el sistema de archivos. Descubrirás cómo abrir archivos, leer su contenido, escribir en ellos y cerrarlos adecuadamente. También discutiremos cómo manejar errores y excepciones relacionados con la lectura y escritura de archivos.", test_letter: "D", completed: false)
lesson_d4 = Lesson.create(number: 19, title: "Estructuras de datos avanzadas en Haskell", description: "Esta lección se enfoca en las estructuras de datos avanzadas en Haskell. Aprenderás sobre las estructuras de datos como árboles binarios y grafos, que son fundamentales para resolver problemas más complejos. Exploraremos cómo implementar y manipular estas estructuras de datos en Haskell, así como las operaciones comunes que puedes realizar en ellas. También discutiremos las ventajas y desventajas de diferentes estructuras de datos según el escenario de uso.", test_letter: "D", completed: false)
lesson_d5 = Lesson.create(number: 20, title: "Programación funcional lazzy en Haskell", description: "Exploraremos el concepto de evaluación lazy en Haskell. Aprenderás que en Haskell, la evaluación lazy significa que los cálculos se realizan solo cuando los resultados son necesarios. Descubrirás cómo la evaluación lazy puede mejorar la eficiencia y la modularidad del código al evitar cálculos innecesarios. Veremos ejemplos de evaluación lazy en Haskell y cómo puedes aprovechar esta característica para escribir programas más eficientes y elegantes.", test_letter: "D", completed: false)

question_d1 = Question.create(number: 16, description: "¿Cómo se manejan las excepciones en Haskell?", well_answered: false, test_letter: "D")
question_d2 = Question.create(number: 17, description: "¿Qué es la programación monádica?", well_answered: false, test_letter: "D")
question_d3 = Question.create(number: 18, description: "¿Cómo se realiza la lectura de archivos en Haskell?", well_answered: false, test_letter: "D")
question_d4 = Question.create(number: 19, description: "¿Cuáles son algunas estructuras de datos avanzadas en Haskell?", well_answered: false, test_letter: "D")
question_d5 = Question.create(number: 20, description: "¿Qué significa la evaluación lazy en Haskell?", well_answered: false, test_letter: "D")

Option.create(number: 46, description: "Utilizando bloques try-catch", question_number: 16, correct: true)
Option.create(number: 47, description: "Utilizando sentencias if-else", question_number: 16, correct: false)
Option.create(number: 48, description: "Utilizando sentencias switch-case", question_number: 16, correct: false)
Option.create(number: 49, description: "Un enfoque de programación basado en monoides", question_number: 17, correct: true)
Option.create(number: 50, description: "Un enfoque de programación basado en bucles", question_number: 17, correct: false)
Option.create(number: 51, description: "Un enfoque de programación basado en condicionales", question_number: 17, correct: false)
Option.create(number: 52, description: "Utilizando la función 'readFile'", question_number: 18, correct: true)
Option.create(number: 53, description: "Utilizando la función 'writeFile'", question_number: 18, correct: false)
Option.create(number: 54, description: "Utilizando la función 'openFile'", question_number: 18, correct: false)
Option.create(number: 55, description: "Árboles binarios y grafos", question_number: 19, correct: true)
Option.create(number: 56, description: "Listas y matrices", question_number: 19, correct: false)
Option.create(number: 57, description: "Colas y pilas", question_number: 19, correct: false)
Option.create(number: 58, description: "La evaluación se realiza solo cuando los resultados son necesarios", question_number: 20, correct: true)
Option.create(number: 59, description: "La evaluación se realiza de manera inmediata", question_number: 20, correct: false)
Option.create(number: 60, description: "La evaluación se realiza en paralelo", question_number: 20, correct: false)

# Test E
test_e = Test.create(letter: "E", description: "Programación avanzada en Haskell", completed: false, cant_questions: 5, acerted_answers: 0)

lesson_e1 = Lesson.create(number: 21, title: "Tipos de datos avanzados en Haskell", description: "En esta lección, exploraremos los tipos de datos avanzados en Haskell. Aprenderás sobre los tipos algebraicos y tipos polimórficos, que te permiten representar estructuras de datos más complejas y expresar conceptos abstractos de manera concisa. Veremos cómo definir y utilizar estos tipos de datos en Haskell, y discutiremos algunas técnicas avanzadas de manipulación de tipos.", test_letter: "E", completed: false)
lesson_e2 = Lesson.create(number: 22, title: "Programación funcional reactiva en Haskell", description: "Aprenderás cómo utilizar la programación funcional reactiva en Haskell. Descubrirás que la programación funcional reactiva es un paradigma basado en eventos que te permite construir aplicaciones reactivas y manejar flujos de datos asincrónicos. Exploraremos los conceptos clave de la programación funcional reactiva, como los eventos, los comportamientos y las señales, y cómo puedes utilizar bibliotecas específicas de Haskell para implementar este estilo de programación.", test_letter: "E", completed: false)
lesson_e3 = Lesson.create(number: 23, title: "Programación concurrente en Haskell", description: "Esta lección se enfoca en la programación concurrente en Haskell. Aprenderás diferentes técnicas para realizar la programación concurrente, como el uso de hilos de ejecución y la comunicación entre ellos. Exploraremos cómo crear y administrar hilos en Haskell, así como las herramientas y abstracciones proporcionadas por el lenguaje para facilitar la programación concurrente. También discutiremos cómo manejar la concurrencia y evitar problemas como las condiciones de carrera y la incoherencia de datos.", test_letter: "E", completed: false)
lesson_e4 = Lesson.create(number: 24, title: "Optimización y rendimiento en Haskell", description: "Aprenderás técnicas de optimización y mejora de rendimiento en Haskell. Descubrirás cómo optimizar bucles y utilizar estructuras de datos eficientes para mejorar el rendimiento de tus programas. Exploraremos técnicas como el desenrollado de bucles, la especialización de tipos y la evaluación estricta, que te permitirán escribir código más eficiente en Haskell. También discutiremos algunas herramientas y técnicas de perfilado para identificar y resolver cuellos de botella en tu código.", test_letter: "E", completed: false)
lesson_e5 = Lesson.create(number: 25, title: "Dependencias externas y extensiones de Haskell", description: "Exploraremos cómo utilizar dependencias externas y extensiones de Haskell. Aprenderás a importar bibliotecas externas en tus proyectos Haskell para aprovechar funcionalidades adicionales y reutilizar código existente. Descubrirás cómo gestionar las dependencias de tu proyecto utilizando herramientas como Cabal o Stack. También discutiremos cómo habilitar y utilizar extensiones de Haskell, que son características adicionales que amplían el lenguaje y te permiten escribir código más expresivo y conciso.", test_letter: "E", completed: false)

question_e1 = Question.create(number: 21, description: "¿Cuáles son los tipos de datos avanzados en Haskell?", well_answered: false, test_letter: "E")
question_e2 = Question.create(number: 22, description: "¿Qué es la programación funcional reactiva?", well_answered: false, test_letter: "E")
question_e3 = Question.create(number: 23, description: "¿Cómo se realiza la programación concurrente en Haskell?", well_answered: false, test_letter: "E")
question_e4 = Question.create(number: 24, description: "¿Qué técnicas se utilizan para la optimización y rendimiento en Haskell?", well_answered: false, test_letter: "E")
question_e5 = Question.create(number: 25, description: "¿Cómo se utilizan dependencias externas y extensiones en Haskell?", well_answered: false, test_letter: "E")

Option.create(number: 61, description: "Tipos algebraicos y tipos polimórficos", question_number: 21, correct: true)
Option.create(number: 62, description: "Tipos básicos y tipos compuestos", question_number: 21, correct: false)
Option.create(number: 63, description: "Tipos numéricos y tipos de cadena", question_number: 21, correct: false)
Option.create(number: 64, description: "Un paradigma de programación basado en eventos", question_number: 22, correct: true)
Option.create(number: 65, description: "Un paradigma de programación basado en objetos", question_number: 22, correct: false)
Option.create(number: 66, description: "Un paradigma de programación basado en funciones", question_number: 22, correct: false)
Option.create(number: 67, description: "Utilizando hilos de ejecución y comunicación entre ellos", question_number: 23, correct: true)
Option.create(number: 68, description: "Utilizando técnicas de paralelismo automático", question_number: 23, correct: false)
Option.create(number: 69, description: "Utilizando memoria compartida y exclusión mutua", question_number: 23, correct: false)
Option.create(number: 70, description: "Optimización de bucles y uso eficiente de estructuras de datos", question_number: 24, correct: true)
Option.create(number: 71, description: "Utilizando técnicas de programación dinámica", question_number: 24, correct: false)
Option.create(number: 72, description: "Utilizando técnicas de memoización", question_number: 24, correct: false)
Option.create(number: 73, description: "A través de importación directa de bibliotecas externas", question_number: 25, correct: true)
Option.create(number: 74, description: "A través de la definición de tipos de datos personalizados", question_number: 25, correct: false)
Option.create(number: 75, description: "A través de la utilización de lenguajes de programación externos", question_number: 25, correct: false)
