require 'sinatra/activerecord'

require_relative 'account'
require_relative 'lesson'
require_relative 'test'
require_relative 'question'
require_relative 'option'
require_relative 'snippet'
require_relative 'account_lesson'
require_relative 'account_test'
require_relative 'account_question'
require_relative 'account_option'
