# frozen_string_literal: true

ruby '2.7.5'

source 'https://rubygems.org'

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end

gem 'rack-session'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sqlite3'

group :test do
  gem 'rspec'
end

gem 'asciidoctor'
gem 'rack-test'
gem 'rubocop'
gem 'simplecov'

group :development, :test do
  gem 'database_cleaner'
end
